export { default as LoginView } from './login-view.vue'
export { default as RegisterView } from './register-view.vue'
export { default as ForgotPasswordView } from './forgot-password-view.vue'
export { default as ResetPasswordView } from './reset-password-view.vue'
export { default as SuccessView } from './success-view.vue'
export { default as VeriyEmailView } from './verify-email-view.vue'
